SCREEN_WIDTH:int = 1000
SCREEN_HEIGHT:int = 700

XP_PER_LEVEL:int = 100

ASTEROID_MIN_RADIUS:int = 20
ASTEROID_KINDS:int = 3
ASTEROID_SPAWN_RATE:float = 0.8  # seconds
ASTEROID_MAX_RADIUS:int = ASTEROID_MIN_RADIUS * ASTEROID_KINDS


PLAYER_RADIUS:int = 10
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200


SHOT_RADIUS:int = 5
PLAYER_SHOOT_SPEED = 600
PLAYER_SHOOT_COOLDOWN:float = 0.3

PLAYER_BOMB_COOLDOWN = 10

BARRIER_RADIUS = 50
BARRIER_DURATION:float = 6.0
PLAYER_BARRIER_COOLDOWN = 10
